# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a942c37caf9a0ee94967d947af0490064bb3bea161e7ccd8b40d4f9cd81bf6f68369adf05b329bf29a751288d5b37254aed3abd2f835df63abaa823f68942c2e

test:
  secret_key_base: ee4426170d0eff67e8249036c2661e911aaa7cbb4578c6678ec6e7df1426a545f0a718246da5e1ff60358b2b60ecdfbd638efbee119f1bef9dd6876bc76e8d00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
